<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="PranushaTarun" failures="1" tests="1" name="Module_Test" time="0.01" errors="0" timestamp="2022-11-28T11:21:47 EST">
  <testcase classname="testng_Suite1.Module1" name="test001" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng_Suite1.Module1.test001(Module1.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test001 -->
  <testcase classname="testng_Suite1.Module2" name="test002" time="0.0">
    <ignored/>
  </testcase> <!-- test002 -->
  <testcase classname="testng_Suite1.Module2" name="test003" time="0.0">
    <ignored/>
  </testcase> <!-- test003 -->
  <testcase classname="testng_Suite1.Module1" name="test002" time="0.0">
    <ignored/>
  </testcase> <!-- test002 -->
  <testcase classname="testng_Suite1.Module1" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="testng_Suite1.Module1" name="test003" time="0.0">
    <ignored/>
  </testcase> <!-- test003 -->
  <testcase classname="testng_Suite1.Module2" name="test001" time="0.0">
    <ignored/>
  </testcase> <!-- test001 -->
</testsuite> <!-- Module_Test -->
